name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: Tests and Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
      - name: Build docs
        run: npm run docs
